### PR TITLE
Site bathymetry schema

### PR DESCRIPTION
**Pull request by kilojoules**
This schema allows bathymetry to be specified as arrays of x, y, and depth, within the YAML file.

### CODE REVIEW

**Review by ptrbortolotti — COMMENTED** [review]
I'd suggest adding more details in the description. For example, in which coordinate system are x and y? Will depth be defined positive or negative? I'd also recommend adding min and max values when available (maybe not for x and y, but yes for depth), and the units (meters), see an example here for the wind turbine rotor diameter 
https://github.com/IEAWindTask37/windIO/blob/0ea5d889c1c6ab5c115325292bfdbb6dcb738a15/windIO/turbine/IEAontology_schema.yaml#L76

Lastly, please update the documentation on readthedocs (here https://github.com/IEAWindTask37/windIO/blob/master/docs/source/plant_energy_site.rst ?)

**Comment by kilojoules** [comment]
@ptrbortolotti Thank you. I have updated the PR according to your feedback.

**Comment by bayc** [comment]
@kilojoules Is it possible to include some example bathymetry data so that these proposed changes can be tested? You can find in `examples/plant/validation.py` code that verifies all the current aspects of the plant ontology with the available example data, and it would be good to include additional code for bathymetry.

**Comment by ptrbortolotti** [comment]
@kilojoules thank you for this! is this PR still up to date? are you hoping to address the last comment from @bayc?

**Comment by kilojoules** [comment]
We discussed it and I am going to try to use the existing constructor. This PR is not ready yet.

**Comment by bayc** [comment]
I have updated the PR to use the included constructor for loading bathymetry data. I've set the default yaml loader to be the `XrResourceLoader`, which supports loading yaml files directly or reading in netCDF files in xarray format.

@kilojoules Please test this out with your wind plant repository and verify that it works.

**Pull request merged**
